Add sticky parameter to the posts endpoint.
WP-API/WP-API pull request #2708
Opened 2016-09-18 21:44 UTC by joehoyle

This allows getting posts that are either "only sticky" for "not sticky"
via `sticky=true` or `sticky=false`. This can also be used in conjunction
with `include` and `exclude`.

2016-09-18 21:45 UTC, joehoyle commented
Fixes #2705

2016-09-19 22:16 UTC, rmccue commented on tests/test-rest-posts-controller.php
> +	}
This test appears to be unrelated to the rest of the PR, can you split it into a new one? :)

2016-09-19 22:16 UTC, rmccue requested changes

2016-09-20 14:45 UTC, joehoyle commented on tests/test-rest-posts-controller.php
> +	}
Ohhhhhh that's why this is failing, doh! Didn't mean to commit this.

2016-09-22 19:12 UTC, rmccue commented on lib/endpoints/class-wp-rest-posts-controller.php
> +				'type'              => 'boolean',
Indentation is off.

2016-09-22 19:13 UTC, rmccue requested changes

2016-09-22 22:59 UTC, rmccue commented
Over to KAdam for review.

2016-09-22 22:59 UTC, rmccue approved these changes

2016-09-23 15:18 UTC, kadamwhite commented on lib/endpoints/class-wp-rest-posts-controller.php
> +		if ( isset( $request['sticky'] ) ) {
As noted in slack, `sticky=false` does not work (it's interpreted as `true` due to string coercion -- suggest using `rest_is_boolean` introduced in #2630

2016-09-23 15:18 UTC, kadamwhite requested changes

2016-09-23 15:20 UTC, kadamwhite commented on tests/test-rest-posts-controller.php
> +	}
Not sure if it's worth it but I think this test (variant of the one above) will demonstrate whether `sticky=false` in query string will work:
```php
	public function test_get_items_not_sticky_query_string_boolean() {
		$id1 = $this->post_id;
		$id2 = $this->factory->post->create( array( 'post_status' => 'publish' ) );

		update_option( 'sticky_posts', array( $id2 ) );

		$request = new WP_REST_Request( 'GET', '/wp/v2/posts' );
		$request->set_param( 'sticky', 'false' );

		$response = $this->server->dispatch( $request );
		$this->assertCount( 1, $response->get_data() );

		$posts = $response->get_data();
		$post = $posts[0];
		$this->assertEquals( $id1, $post['id'] );
	}
```

2016-09-23 16:38 UTC, BE-Webdesign commented on lib/endpoints/class-wp-rest-posts-controller.php
> +				'type'        => 'boolean',
Add in the `rest_validate_request_arg` and `rest_sanitize_request_arg` for validate and sanitize callbacks and this patch will be da hotness!

2016-09-23 16:38 UTC, BE-Webdesign requested changes

2016-09-23 16:45 UTC, kadamwhite commented on tests/test-rest-posts-controller.php
> +	}
After discussion w/ @BE-Webdesign & @rmccue testing this case independently is probably overkill once the right sanitize callback is put in place

2016-09-28 14:59 UTC, joehoyle commented on lib/endpoints/class-wp-rest-posts-controller.php
> +				'type'        => 'boolean',
This will automajically be done based off the schema already.

2016-09-28 15:01 UTC, joehoyle commented on lib/endpoints/class-wp-rest-posts-controller.php
> +				'type'        => 'boolean',
Actually this is not the schema, sorry my bad!

2016-09-28 15:43 UTC, joehoyle commented
@rmccue @BE-Webdesign @kadamwhite ok I pushed an update to fix the `false` in the URL thang.

2016-09-28 16:29 UTC, kadamwhite approved these changes

2016-09-28 16:29 UTC, kadamwhite commented
+1 from me, `sticky=false` now works as expected

2016-09-28 18:28 UTC, BE-Webdesign approved these changes

2016-09-28 18:28 UTC, merged