Use wp_kses in place of wp_filter_post_kses to sanitize post title
WP-API/WP-API pull request #2840
Opened 2016-10-15 19:13 UTC by kadamwhite

May fix #2788

This PR switches from using `wp_filter_post_kses()` for `post_title` sanitization to calling `wp_kses` directly: #2788 describes that the core behavior is to call `wp_filter_kses()`, but @westonruter notes in that thread that the slash handling in `wp_filter_kses` is lossy so using the underlying implementation of `wp_filter_kses` without the de-slashing and re-slashing should provide adequate sanitization without compromising the integrity of the content.

Review requested especially from @rachelbaker or @westonruter

2016-10-15 19:29 UTC, westonruter requested changes

2016-10-15 19:29 UTC, westonruter commented on lib/endpoints/class-wp-rest-posts-controller.php
> +				$prepared_post->post_title = wp_kses( $request['title'], current_filter() );
I think that `current_filter()` should be replaced with `'post'`. I'm not sure if there are filters being applied at this point, but even if they are, for sure they're not going to be the same as what are being applied during a call to `sanitize_post()`.

2016-10-15 19:29 UTC, westonruter commented on lib/endpoints/class-wp-rest-posts-controller.php
> +				$prepared_post->post_title = wp_kses( $request['title']['raw'], current_filter() );
″

2016-10-15 20:14 UTC, rachelbaker commented on lib/endpoints/class-wp-rest-posts-controller.php
> +				$prepared_post->post_title = wp_kses( $request['title'], current_filter() );
I thought `current_filter()` here should be `title_save_pre` because post titles get a stricter set of HTML tags allowed than `wp_kses_post()`

2016-10-16 06:16 UTC, westonruter commented on lib/endpoints/class-wp-rest-posts-controller.php
> +				$prepared_post->post_title = wp_kses( $request['title'], current_filter() );
You're probably right. So the string literal `'title_save_pre'` should be used instead of `current_filter()`.

2016-10-16 17:00 UTC, kadamwhite commented
@rachelbaker @westonruter thank you for clarifying, that makes sense. I've updated the patch

2016-10-17 14:38 UTC, rachelbaker commented
@kadamwhite we use `wp_filter_post_kses()` in several other places within the endpoints.
So if we are not trusting the slash handling of `wp_filter_post_kses()` then we  should do that consistently, and switch to `wp_kses_post()`

2016-10-17 14:43 UTC, rachelbaker commented
@kadamwhite Only thing blocking this would be a unit test.

2016-10-17 14:45 UTC, kadamwhite commented
Unit test would be e.g. create a post w/ a title including a disallowed HTML tag such as `<div>`, and ensure it is stripped

2016-10-17 19:36 UTC, kadamwhite commented on tests/test-rest-posts-controller.php
> +		$this->assertEquals( '\o/', $new_data['title']['raw'] );
@westonruter @rachelbaker This test fails, but I would have expected it to pass based on our discussion previously. Any ideas?

2016-10-18 00:59 UTC, rachelbaker commented on tests/test-rest-posts-controller.php
> +		$this->assertEquals( '\o/', $new_data['title']['raw'] );
@kadamwhite My guess would be that`wp_kses_no_null()` (called in `wp_kses()`)  is stripping out the preceding slash.

2016-10-18 13:38 UTC, kadamwhite commented on tests/test-rest-posts-controller.php
> +		$this->assertEquals( '\o/', $new_data['title']['raw'] );
If we can't escape (har har) the unslashing, is the use of `wp_kses` overkill? if you can suggest a direction I will implement.

2016-10-18 13:40 UTC, rachelbaker commented on tests/test-rest-posts-controller.php
> +		$this->assertEquals( '\o/', $new_data['title']['raw'] );
@kadamwhite crazy idea, what happens if you run this test with `wp_filter_kses` instead?

2016-10-18 15:00 UTC, kadamwhite commented on tests/test-rest-posts-controller.php
> +		$this->assertEquals( '\o/', $new_data['title']['raw'] );
Same thing

2016-10-18 16:18 UTC, rachelbaker commented on tests/test-rest-posts-controller.php
> +		$this->assertEquals( '\o/', $new_data['title']['raw'] );
@kadamwhite yeah, I tested it too and was not able to get a passing test.  😞 
I also WAS able to confirm that within the WP editor I can save a post with a title of `Do what I mean \ Not what I say`, and that is also exactly how the data is stored in the db.  So we are doing something WRONG somewhere here.

2016-10-19 06:08 UTC, rmccue commented on tests/test-rest-posts-controller.php
> +		$this->assertEquals( '\o/', $new_data['title']['raw'] );
This is potentially an issue because of the unescaped slash? Try `\\o/` instead?

2016-10-19 15:02 UTC, kadamwhite commented on tests/test-rest-posts-controller.php
> +		$this->assertEquals( '\o/', $new_data['title']['raw'] );
@rmccue Same results with `'\\o/'`, with both wp_filter_kses and wp_kses

2016-12-05 19:59 UTC, kadamwhite commented
Closing, as I believe this has been superseded by 4.7 trunk

2016-12-05 19:59 UTC, closed without merging