Send an error if the client tries to delete an option with an non-scaler
WP-API/WP-API pull request #2851
Opened 2016-10-17 18:40 UTC by joehoyle

This is to cover the case when there is an invalid option value in the database that does not match the one in register_setting(). 

Currently we are only doing this check for setting values to `null` to work around the Client-sends-the-same-response issue, but we _do_ all setting the value to some other value.

2016-10-17 19:05 UTC, rachelbaker commented on lib/endpoints/class-wp-rest-settings-controller.php
> +			// However, bacause a saved "invalid" value in the database will
@joehoyle Typo here.  bacause -> because

2016-10-17 19:34 UTC, kadamwhite commented
@joehoyle Looks like this addresses #2838, is that the correct issue for this PR?

2016-10-19 05:48 UTC, rmccue requested changes

2016-10-19 05:48 UTC, rmccue commented on lib/endpoints/class-wp-rest-settings-controller.php
> +		// if the value is not a scaler, it's not possible to cast it to anything.
"scaler" -> "scalar"

2016-10-19 05:48 UTC, rmccue commented on lib/endpoints/class-wp-rest-settings-controller.php
> +						sprintf( __( 'The %s property has an invalid stored value, and was not able to be updated to null.' ), $name ),
"was not able to be updated to null" -> "cannot be updated"

2016-10-19 17:17 UTC, rachelbaker commented
@rmccue #reviewmerge I addressed your feedback items, please review the changes when you can.

2016-10-27 16:09 UTC, rachelbaker commented
Committed https://core.trac.wordpress.org/changeset/38982

2016-10-27 16:09 UTC, closed without merging